<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/msi/system_status.proto

namespace GPBMetadata\Services\Msi;

class SystemStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Msi\Product::initOnce();
        $pool->internalAddGeneratedFile(
            '
¿
 services/msi/system_status.protoservices.msi"
GetProductsRequest"<
GetProductsResponse%
products (2.models.msi.ProductB1Z/github.com/s77rt/rdpcloud/proto/go/services/msibproto3'
        , true);

        static::$is_initialized = true;
    }
}

