<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/shutdown/system_shutdown.proto

namespace Services\Shutdown;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.shutdown.AbortSystemShutdownRequest</code>
 */
class AbortSystemShutdownRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Shutdown\SystemShutdown::initOnce();
        parent::__construct($data);
    }

}

