<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/msi/product.proto

namespace GPBMetadata\Models\Msi;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ü
models/msi/product.proto
models.msi"{
Product
guid (	
name (	
version (	
	publisher (	0
install_date (2.google.protobuf.TimestampB/Z-github.com/s77rt/rdpcloud/proto/go/models/msibproto3'
        , true);

        static::$is_initialized = true;
    }
}

