// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: services/shutdown/system_shutdown.proto

package shutdown

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateSystemShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timeout uint32 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Force   bool   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	Reboot  bool   `protobuf:"varint,4,opt,name=reboot,proto3" json:"reboot,omitempty"`
	Reason  uint32 `protobuf:"varint,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *InitiateSystemShutdownRequest) Reset() {
	*x = InitiateSystemShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_shutdown_system_shutdown_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateSystemShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSystemShutdownRequest) ProtoMessage() {}

func (x *InitiateSystemShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_shutdown_system_shutdown_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSystemShutdownRequest.ProtoReflect.Descriptor instead.
func (*InitiateSystemShutdownRequest) Descriptor() ([]byte, []int) {
	return file_services_shutdown_system_shutdown_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateSystemShutdownRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitiateSystemShutdownRequest) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *InitiateSystemShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *InitiateSystemShutdownRequest) GetReboot() bool {
	if x != nil {
		return x.Reboot
	}
	return false
}

func (x *InitiateSystemShutdownRequest) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type InitiateSystemShutdownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitiateSystemShutdownResponse) Reset() {
	*x = InitiateSystemShutdownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_shutdown_system_shutdown_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateSystemShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSystemShutdownResponse) ProtoMessage() {}

func (x *InitiateSystemShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_shutdown_system_shutdown_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSystemShutdownResponse.ProtoReflect.Descriptor instead.
func (*InitiateSystemShutdownResponse) Descriptor() ([]byte, []int) {
	return file_services_shutdown_system_shutdown_proto_rawDescGZIP(), []int{1}
}

type AbortSystemShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortSystemShutdownRequest) Reset() {
	*x = AbortSystemShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_shutdown_system_shutdown_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortSystemShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSystemShutdownRequest) ProtoMessage() {}

func (x *AbortSystemShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_shutdown_system_shutdown_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSystemShutdownRequest.ProtoReflect.Descriptor instead.
func (*AbortSystemShutdownRequest) Descriptor() ([]byte, []int) {
	return file_services_shutdown_system_shutdown_proto_rawDescGZIP(), []int{2}
}

type AbortSystemShutdownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortSystemShutdownResponse) Reset() {
	*x = AbortSystemShutdownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_shutdown_system_shutdown_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortSystemShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSystemShutdownResponse) ProtoMessage() {}

func (x *AbortSystemShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_shutdown_system_shutdown_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSystemShutdownResponse.ProtoReflect.Descriptor instead.
func (*AbortSystemShutdownResponse) Descriptor() ([]byte, []int) {
	return file_services_shutdown_system_shutdown_proto_rawDescGZIP(), []int{3}
}

var File_services_shutdown_system_shutdown_proto protoreflect.FileDescriptor

var file_services_shutdown_system_shutdown_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x22, 0x99, 0x01, 0x0a,
	0x1d, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x62, 0x6f,
	0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x62, 0x6f, 0x6f, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x1e, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64, 0x70, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_shutdown_system_shutdown_proto_rawDescOnce sync.Once
	file_services_shutdown_system_shutdown_proto_rawDescData = file_services_shutdown_system_shutdown_proto_rawDesc
)

func file_services_shutdown_system_shutdown_proto_rawDescGZIP() []byte {
	file_services_shutdown_system_shutdown_proto_rawDescOnce.Do(func() {
		file_services_shutdown_system_shutdown_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_shutdown_system_shutdown_proto_rawDescData)
	})
	return file_services_shutdown_system_shutdown_proto_rawDescData
}

var file_services_shutdown_system_shutdown_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_shutdown_system_shutdown_proto_goTypes = []interface{}{
	(*InitiateSystemShutdownRequest)(nil),  // 0: services.shutdown.InitiateSystemShutdownRequest
	(*InitiateSystemShutdownResponse)(nil), // 1: services.shutdown.InitiateSystemShutdownResponse
	(*AbortSystemShutdownRequest)(nil),     // 2: services.shutdown.AbortSystemShutdownRequest
	(*AbortSystemShutdownResponse)(nil),    // 3: services.shutdown.AbortSystemShutdownResponse
}
var file_services_shutdown_system_shutdown_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_shutdown_system_shutdown_proto_init() }
func file_services_shutdown_system_shutdown_proto_init() {
	if File_services_shutdown_system_shutdown_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_shutdown_system_shutdown_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateSystemShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_shutdown_system_shutdown_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateSystemShutdownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_shutdown_system_shutdown_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortSystemShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_shutdown_system_shutdown_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortSystemShutdownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_shutdown_system_shutdown_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_shutdown_system_shutdown_proto_goTypes,
		DependencyIndexes: file_services_shutdown_system_shutdown_proto_depIdxs,
		MessageInfos:      file_services_shutdown_system_shutdown_proto_msgTypes,
	}.Build()
	File_services_shutdown_system_shutdown_proto = out.File
	file_services_shutdown_system_shutdown_proto_rawDesc = nil
	file_services_shutdown_system_shutdown_proto_goTypes = nil
	file_services_shutdown_system_shutdown_proto_depIdxs = nil
}
