<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/netmgmt/local_group.proto

namespace GPBMetadata\Models\Netmgmt;

class LocalGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
³
 models/netmgmt/local_group.protomodels.netmgmt"

LocalGroup
	groupname (	"!
LocalGroup_1
	groupname (	B3Z1github.com/s77rt/rdpcloud/proto/go/models/netmgmtbproto3'
        , true);

        static::$is_initialized = true;
    }
}

