// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: services/msi/msi.proto

package msi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsiClient is the client API for Msi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsiClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type msiClient struct {
	cc grpc.ClientConnInterface
}

func NewMsiClient(cc grpc.ClientConnInterface) MsiClient {
	return &msiClient{cc}
}

func (c *msiClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/services.msi.Msi/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsiServer is the server API for Msi service.
// All implementations must embed UnimplementedMsiServer
// for forward compatibility
type MsiServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	mustEmbedUnimplementedMsiServer()
}

// UnimplementedMsiServer must be embedded to have forward compatible implementations.
type UnimplementedMsiServer struct {
}

func (UnimplementedMsiServer) GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedMsiServer) mustEmbedUnimplementedMsiServer() {}

// UnsafeMsiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsiServer will
// result in compilation errors.
type UnsafeMsiServer interface {
	mustEmbedUnimplementedMsiServer()
}

func RegisterMsiServer(s grpc.ServiceRegistrar, srv MsiServer) {
	s.RegisterService(&Msi_ServiceDesc, srv)
}

func _Msi_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsiServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.msi.Msi/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsiServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Msi_ServiceDesc is the grpc.ServiceDesc for Msi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.msi.Msi",
	HandlerType: (*MsiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _Msi_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/msi/msi.proto",
}
