<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/fileio/quota_entry.proto

namespace GPBMetadata\Models\Fileio;

class QuotaEntry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
models/fileio/quota_entry.protomodels.fileio"x

QuotaEntry
username (	
quota_threshold (
quota_limit (

quota_used (
account_status ("<
QuotaEntry_6
quota_threshold (
quota_limit ("i
QuotaEntry_30
quota_threshold (
quota_limit (

quota_used (
account_status (B2Z0github.com/s77rt/rdpcloud/proto/go/models/fileiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

