<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/fileio/user.proto

namespace GPBMetadata\Models\Fileio;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
›
models/fileio/user.protomodels.fileio"
User
username (	"
User_1
username (	B2Z0github.com/s77rt/rdpcloud/proto/go/models/fileiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

