// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: services/netmgmt/netmgmt.proto

package netmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetmgmtClient is the client API for Netmgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetmgmtClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
}

type netmgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewNetmgmtClient(cc grpc.ClientConnInterface) NetmgmtClient {
	return &netmgmtClient{cc}
}

func (c *netmgmtClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/services.netmgmt.Netmgmt/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netmgmtClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/services.netmgmt.Netmgmt/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetmgmtServer is the server API for Netmgmt service.
// All implementations must embed UnimplementedNetmgmtServer
// for forward compatibility
type NetmgmtServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	mustEmbedUnimplementedNetmgmtServer()
}

// UnimplementedNetmgmtServer must be embedded to have forward compatible implementations.
type UnimplementedNetmgmtServer struct {
}

func (UnimplementedNetmgmtServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedNetmgmtServer) AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNetmgmtServer) mustEmbedUnimplementedNetmgmtServer() {}

// UnsafeNetmgmtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetmgmtServer will
// result in compilation errors.
type UnsafeNetmgmtServer interface {
	mustEmbedUnimplementedNetmgmtServer()
}

func RegisterNetmgmtServer(s grpc.ServiceRegistrar, srv NetmgmtServer) {
	s.RegisterService(&Netmgmt_ServiceDesc, srv)
}

func _Netmgmt_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.netmgmt.Netmgmt/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netmgmt_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetmgmtServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.netmgmt.Netmgmt/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetmgmtServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Netmgmt_ServiceDesc is the grpc.ServiceDesc for Netmgmt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Netmgmt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.netmgmt.Netmgmt",
	HandlerType: (*NetmgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _Netmgmt_GetUsers_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Netmgmt_AddUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/netmgmt/netmgmt.proto",
}
