<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/fileio/quota_entry.proto

namespace Models\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>models.fileio.QuotaEntry_30</code>
 */
class QuotaEntry_30 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 quota_threshold = 2;</code>
     */
    protected $quota_threshold = 0;
    /**
     * Generated from protobuf field <code>int64 quota_limit = 3;</code>
     */
    protected $quota_limit = 0;
    /**
     * Generated from protobuf field <code>int64 quota_used = 4;</code>
     */
    protected $quota_used = 0;
    /**
     * Generated from protobuf field <code>uint32 account_status = 5;</code>
     */
    protected $account_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $quota_threshold
     *     @type int|string $quota_limit
     *     @type int|string $quota_used
     *     @type int $account_status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Models\Fileio\QuotaEntry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 quota_threshold = 2;</code>
     * @return int|string
     */
    public function getQuotaThreshold()
    {
        return $this->quota_threshold;
    }

    /**
     * Generated from protobuf field <code>int64 quota_threshold = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuotaThreshold($var)
    {
        GPBUtil::checkInt64($var);
        $this->quota_threshold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 quota_limit = 3;</code>
     * @return int|string
     */
    public function getQuotaLimit()
    {
        return $this->quota_limit;
    }

    /**
     * Generated from protobuf field <code>int64 quota_limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuotaLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->quota_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 quota_used = 4;</code>
     * @return int|string
     */
    public function getQuotaUsed()
    {
        return $this->quota_used;
    }

    /**
     * Generated from protobuf field <code>int64 quota_used = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuotaUsed($var)
    {
        GPBUtil::checkInt64($var);
        $this->quota_used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 account_status = 5;</code>
     * @return int
     */
    public function getAccountStatus()
    {
        return $this->account_status;
    }

    /**
     * Generated from protobuf field <code>uint32 account_status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->account_status = $var;

        return $this;
    }

}

