<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/shutdown/system_shutdown.proto

namespace Services\Shutdown;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.shutdown.InitiateSystemShutdownRequest</code>
 */
class InitiateSystemShutdownRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>uint32 timeout = 2;</code>
     */
    protected $timeout = 0;
    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     */
    protected $force = false;
    /**
     * Generated from protobuf field <code>bool reboot = 4;</code>
     */
    protected $reboot = false;
    /**
     * Generated from protobuf field <code>uint32 reason = 5;</code>
     */
    protected $reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type int $timeout
     *     @type bool $force
     *     @type bool $reboot
     *     @type int $reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Shutdown\SystemShutdown::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 2;</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     * @return bool
     */
    public function getForce()
    {
        return $this->force;
    }

    /**
     * Generated from protobuf field <code>bool force = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setForce($var)
    {
        GPBUtil::checkBool($var);
        $this->force = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reboot = 4;</code>
     * @return bool
     */
    public function getReboot()
    {
        return $this->reboot;
    }

    /**
     * Generated from protobuf field <code>bool reboot = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setReboot($var)
    {
        GPBUtil::checkBool($var);
        $this->reboot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 reason = 5;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>uint32 reason = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkUint32($var);
        $this->reason = $var;

        return $this;
    }

}

