<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/disk_management.proto

namespace GPBMetadata\Services\Fileio;

class DiskManagement
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Fileio\QuotaEntry::initOnce();
        \GPBMetadata\Models\Fileio\User::initOnce();
        $pool->internalAddGeneratedFile(
            '
’

%services/fileio/disk_management.protoservices.fileiomodels/fileio/user.proto"+
GetQuotaStateRequest
volume_path (	",
GetQuotaStateResponse
quota_state ("@
SetQuotaStateRequest
volume_path (	
quota_state ("
SetQuotaStateResponse"-
GetDefaultQuotaRequest
volume_path (	"M
GetDefaultQuotaResponse2
default_quota (2.models.fileio.QuotaEntry_6"a
SetDefaultQuotaRequest
volume_path (	2
default_quota (2.models.fileio.QuotaEntry_6"
SetDefaultQuotaResponse"2
GetUsersQuotaEntriesRequest
volume_path (	"P
GetUsersQuotaEntriesResponse0
quota_entries (2.models.fileio.QuotaEntry"T
GetUserQuotaEntryRequest
volume_path (	#
user (2.models.fileio.User_1"N
GetUserQuotaEntryResponse1
quota_entry (2.models.fileio.QuotaEntry_30"1
GetMyUserQuotaEntryRequest
volume_path (	"P
GetMyUserQuotaEntryResponse1
quota_entry (2.models.fileio.QuotaEntry_30"†
SetUserQuotaEntryRequest
volume_path (	#
user (2.models.fileio.User_10
quota_entry (2.models.fileio.QuotaEntry_6"
SetUserQuotaEntryResponse"W
DeleteUserQuotaEntryRequest
volume_path (	#
user (2.models.fileio.User_1"
DeleteUserQuotaEntryResponseB4Z2github.com/s77rt/rdpcloud/proto/go/services/fileiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

