<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/volume_management.proto

namespace GPBMetadata\Services\Fileio;

class VolumeManagement
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Fileio\Volume::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ë
\'services/fileio/volume_management.protoservices.fileio"
GetVolumesRequest"<
GetVolumesResponse&
volumes (2.models.fileio.VolumeB4Z2github.com/s77rt/rdpcloud/proto/go/services/fileiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

