<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/termserv/remote_desktop_services_api.proto

namespace Services\Termserv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.termserv.LogoffUserRequest</code>
 */
class LogoffUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.models.termserv.User_1 user = 1;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Models\Termserv\User_1 $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Termserv\RemoteDesktopServicesApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.models.termserv.User_1 user = 1;</code>
     * @return \Models\Termserv\User_1|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.models.termserv.User_1 user = 1;</code>
     * @param \Models\Termserv\User_1 $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Models\Termserv\User_1::class);
        $this->user = $var;

        return $this;
    }

}

