<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/termserv/remote_desktop_services_api.proto

namespace Services\Termserv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.termserv.LogoffMyUserRequest</code>
 */
class LogoffMyUserRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Termserv\RemoteDesktopServicesApi::initOnce();
        parent::__construct($data);
    }

}

