<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/fileio/volume.proto

namespace GPBMetadata\Models\Fileio;

class Volume
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ž
models/fileio/volume.protomodels.fileio"%
Volume
guid (	
paths (	B2Z0github.com/s77rt/rdpcloud/proto/go/models/fileiobproto3'
        , true);

        static::$is_initialized = true;
    }
}

