<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/termserv/wtsapi32.proto

namespace GPBMetadata\Services\Termserv;

class Wtsapi32
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Termserv\User::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ç
 services/termserv/wtsapi32.protoservices.termserv":
LogoffUserRequest%
user (2.models.termserv.User_1"
LogoffUserResponseB6Z4github.com/s77rt/rdpcloud/proto/go/services/termservbproto3'
        , true);

        static::$is_initialized = true;
    }
}

