<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/sysinfo/time.proto

namespace Services\Sysinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.sysinfo.GetUptimeResponse</code>
 */
class GetUptimeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 uptime = 1;</code>
     */
    protected $uptime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uptime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Sysinfo\Time::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 1;</code>
     * @return int|string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkUint64($var);
        $this->uptime = $var;

        return $this;
    }

}

