<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/disk_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.GetQuotaStateResponse</code>
 */
class GetQuotaStateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 quota_state = 1;</code>
     */
    protected $quota_state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $quota_state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\DiskManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 quota_state = 1;</code>
     * @return int
     */
    public function getQuotaState()
    {
        return $this->quota_state;
    }

    /**
     * Generated from protobuf field <code>uint32 quota_state = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setQuotaState($var)
    {
        GPBUtil::checkUint32($var);
        $this->quota_state = $var;

        return $this;
    }

}

