<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/disk_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.GetUserQuotaEntryResponse</code>
 */
class GetUserQuotaEntryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_30 quota_entry = 1;</code>
     */
    protected $quota_entry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Models\Fileio\QuotaEntry_30 $quota_entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\DiskManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_30 quota_entry = 1;</code>
     * @return \Models\Fileio\QuotaEntry_30|null
     */
    public function getQuotaEntry()
    {
        return $this->quota_entry;
    }

    public function hasQuotaEntry()
    {
        return isset($this->quota_entry);
    }

    public function clearQuotaEntry()
    {
        unset($this->quota_entry);
    }

    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_30 quota_entry = 1;</code>
     * @param \Models\Fileio\QuotaEntry_30 $var
     * @return $this
     */
    public function setQuotaEntry($var)
    {
        GPBUtil::checkMessage($var, \Models\Fileio\QuotaEntry_30::class);
        $this->quota_entry = $var;

        return $this;
    }

}

