<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/volume_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.GetVolumesRequest</code>
 */
class GetVolumesRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\VolumeManagement::initOnce();
        parent::__construct($data);
    }

}

