<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/sysinfo/time.proto

namespace Services\Sysinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.sysinfo.GetUptimeRequest</code>
 */
class GetUptimeRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Sysinfo\Time::initOnce();
        parent::__construct($data);
    }

}

