<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/msi/system_status.proto

namespace Services\Msi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.msi.GetProductsResponse</code>
 */
class GetProductsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .models.msi.Product products = 1;</code>
     */
    private $products;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Models\Msi\Product>|\Google\Protobuf\Internal\RepeatedField $products
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Msi\SystemStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .models.msi.Product products = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Generated from protobuf field <code>repeated .models.msi.Product products = 1;</code>
     * @param array<\Models\Msi\Product>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProducts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Models\Msi\Product::class);
        $this->products = $arr;

        return $this;
    }

}

