<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/msi/system_status.proto

namespace Services\Msi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.msi.GetProductsRequest</code>
 */
class GetProductsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Msi\SystemStatus::initOnce();
        parent::__construct($data);
    }

}

