<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/secauthn/user.proto

namespace GPBMetadata\Models\Secauthn;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
models/secauthn/user.protomodels.secauthn"*
User
username (	
password (	",
User_3
username (	
password (	B4Z2github.com/s77rt/rdpcloud/proto/go/models/secauthnbproto3'
        , true);

        static::$is_initialized = true;
    }
}

