// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: services/termserv/wtsapi32.proto

package termserv

import (
	termserv "github.com/s77rt/rdpcloud/proto/go/models/termserv"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogoffUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *termserv.User_1 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LogoffUserRequest) Reset() {
	*x = LogoffUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_termserv_wtsapi32_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoffUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoffUserRequest) ProtoMessage() {}

func (x *LogoffUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_termserv_wtsapi32_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoffUserRequest.ProtoReflect.Descriptor instead.
func (*LogoffUserRequest) Descriptor() ([]byte, []int) {
	return file_services_termserv_wtsapi32_proto_rawDescGZIP(), []int{0}
}

func (x *LogoffUserRequest) GetUser() *termserv.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoffUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoffUserResponse) Reset() {
	*x = LogoffUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_termserv_wtsapi32_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoffUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoffUserResponse) ProtoMessage() {}

func (x *LogoffUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_termserv_wtsapi32_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoffUserResponse.ProtoReflect.Descriptor instead.
func (*LogoffUserResponse) Descriptor() ([]byte, []int) {
	return file_services_termserv_wtsapi32_proto_rawDescGZIP(), []int{1}
}

var File_services_termserv_wtsapi32_proto protoreflect.FileDescriptor

var file_services_termserv_wtsapi32_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x73,
	0x65, 0x72, 0x76, 0x2f, 0x77, 0x74, 0x73, 0x61, 0x70, 0x69, 0x33, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x74, 0x65, 0x72,
	0x6d, 0x73, 0x65, 0x72, 0x76, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x74, 0x65,
	0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x40, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x6f, 0x66, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x31, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x6f, 0x66, 0x66, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64,
	0x70, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x65, 0x72,
	0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_termserv_wtsapi32_proto_rawDescOnce sync.Once
	file_services_termserv_wtsapi32_proto_rawDescData = file_services_termserv_wtsapi32_proto_rawDesc
)

func file_services_termserv_wtsapi32_proto_rawDescGZIP() []byte {
	file_services_termserv_wtsapi32_proto_rawDescOnce.Do(func() {
		file_services_termserv_wtsapi32_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_termserv_wtsapi32_proto_rawDescData)
	})
	return file_services_termserv_wtsapi32_proto_rawDescData
}

var file_services_termserv_wtsapi32_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_termserv_wtsapi32_proto_goTypes = []interface{}{
	(*LogoffUserRequest)(nil),  // 0: services.termserv.LogoffUserRequest
	(*LogoffUserResponse)(nil), // 1: services.termserv.LogoffUserResponse
	(*termserv.User_1)(nil),    // 2: models.termserv.User_1
}
var file_services_termserv_wtsapi32_proto_depIdxs = []int32{
	2, // 0: services.termserv.LogoffUserRequest.user:type_name -> models.termserv.User_1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_termserv_wtsapi32_proto_init() }
func file_services_termserv_wtsapi32_proto_init() {
	if File_services_termserv_wtsapi32_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_termserv_wtsapi32_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoffUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_termserv_wtsapi32_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoffUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_termserv_wtsapi32_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_termserv_wtsapi32_proto_goTypes,
		DependencyIndexes: file_services_termserv_wtsapi32_proto_depIdxs,
		MessageInfos:      file_services_termserv_wtsapi32_proto_msgTypes,
	}.Build()
	File_services_termserv_wtsapi32_proto = out.File
	file_services_termserv_wtsapi32_proto_rawDesc = nil
	file_services_termserv_wtsapi32_proto_goTypes = nil
	file_services_termserv_wtsapi32_proto_depIdxs = nil
}
