<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/disk_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.GetUsersQuotaEntriesResponse</code>
 */
class GetUsersQuotaEntriesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .models.fileio.QuotaEntry quota_entries = 1;</code>
     */
    private $quota_entries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Models\Fileio\QuotaEntry>|\Google\Protobuf\Internal\RepeatedField $quota_entries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\DiskManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .models.fileio.QuotaEntry quota_entries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQuotaEntries()
    {
        return $this->quota_entries;
    }

    /**
     * Generated from protobuf field <code>repeated .models.fileio.QuotaEntry quota_entries = 1;</code>
     * @param array<\Models\Fileio\QuotaEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQuotaEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Models\Fileio\QuotaEntry::class);
        $this->quota_entries = $arr;

        return $this;
    }

}

