<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/volume_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.GetVolumesResponse</code>
 */
class GetVolumesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .models.fileio.Volume volumes = 1;</code>
     */
    private $volumes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Models\Fileio\Volume>|\Google\Protobuf\Internal\RepeatedField $volumes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\VolumeManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .models.fileio.Volume volumes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVolumes()
    {
        return $this->volumes;
    }

    /**
     * Generated from protobuf field <code>repeated .models.fileio.Volume volumes = 1;</code>
     * @param array<\Models\Fileio\Volume>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVolumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Models\Fileio\Volume::class);
        $this->volumes = $arr;

        return $this;
    }

}

