<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/fileio/disk_management.proto

namespace Services\Fileio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.fileio.SetUserQuotaEntryRequest</code>
 */
class SetUserQuotaEntryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string volume_path = 1;</code>
     */
    protected $volume_path = '';
    /**
     * Generated from protobuf field <code>.models.fileio.User_1 user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_6 quota_entry = 3;</code>
     */
    protected $quota_entry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $volume_path
     *     @type \Models\Fileio\User_1 $user
     *     @type \Models\Fileio\QuotaEntry_6 $quota_entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Fileio\DiskManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string volume_path = 1;</code>
     * @return string
     */
    public function getVolumePath()
    {
        return $this->volume_path;
    }

    /**
     * Generated from protobuf field <code>string volume_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVolumePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->volume_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.models.fileio.User_1 user = 2;</code>
     * @return \Models\Fileio\User_1|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.models.fileio.User_1 user = 2;</code>
     * @param \Models\Fileio\User_1 $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Models\Fileio\User_1::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_6 quota_entry = 3;</code>
     * @return \Models\Fileio\QuotaEntry_6|null
     */
    public function getQuotaEntry()
    {
        return $this->quota_entry;
    }

    public function hasQuotaEntry()
    {
        return isset($this->quota_entry);
    }

    public function clearQuotaEntry()
    {
        unset($this->quota_entry);
    }

    /**
     * Generated from protobuf field <code>.models.fileio.QuotaEntry_6 quota_entry = 3;</code>
     * @param \Models\Fileio\QuotaEntry_6 $var
     * @return $this
     */
    public function setQuotaEntry($var)
    {
        GPBUtil::checkMessage($var, \Models\Fileio\QuotaEntry_6::class);
        $this->quota_entry = $var;

        return $this;
    }

}

