<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/shell/nongrouped.proto

namespace GPBMetadata\Services\Shell;

class Nongrouped
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¬
services/shell/nongrouped.protoservices.shell"#
DeleteProfileRequest
sid (	"
DeleteProfileResponseB3Z1github.com/s77rt/rdpcloud/proto/go/services/shellbproto3'
        , true);

        static::$is_initialized = true;
    }
}

