<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/termserv/user.proto

namespace GPBMetadata\Models\Termserv;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¡
models/termserv/user.protomodels.termserv"
User
username (	"
User_1
username (	B4Z2github.com/s77rt/rdpcloud/proto/go/models/termservbproto3'
        , true);

        static::$is_initialized = true;
    }
}

