<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/netmgmt/local_group.proto

namespace GPBMetadata\Services\Netmgmt;

class LocalGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Netmgmt\LocalGroup::initOnce();
        \GPBMetadata\Models\Netmgmt\User::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ä
"services/netmgmt/local_group.protoservices.netmgmtmodels/netmgmt/user.proto"u
AddUserToLocalGroupRequest$
user (2.models.netmgmt.User_11
local_group (2.models.netmgmt.LocalGroup_1"
AddUserToLocalGroupResponse"z
RemoveUserFromLocalGroupRequest$
user (2.models.netmgmt.User_11
local_group (2.models.netmgmt.LocalGroup_1""
 RemoveUserFromLocalGroupResponse"
GetLocalGroupsRequest"J
GetLocalGroupsResponse0
local_groups (2.models.netmgmt.LocalGroup"P
GetUsersInLocalGroupRequest1
local_group (2.models.netmgmt.LocalGroup_1"E
GetUsersInLocalGroupResponse%
users (2.models.netmgmt.User_1B5Z3github.com/s77rt/rdpcloud/proto/go/services/netmgmtbproto3'
        , true);

        static::$is_initialized = true;
    }
}

