<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/netmgmt/user.proto

namespace GPBMetadata\Services\Netmgmt;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Models\Netmgmt\User::initOnce();
        \GPBMetadata\Models\Netmgmt\LocalGroup::initOnce();
        $pool->internalAddGeneratedFile(
            '
Å
services/netmgmt/user.protoservices.netmgmt models/netmgmt/local_group.proto"6
AddUserRequest$
user (2.models.netmgmt.User_3"
AddUserResponse"9
DeleteUserRequest$
user (2.models.netmgmt.User_1"
DeleteUserResponse"
GetUsersRequest"7
GetUsersResponse#
users (2.models.netmgmt.User"6
GetUserRequest$
user (2.models.netmgmt.User_1"5
GetUserResponse"
user (2.models.netmgmt.User"A
GetUserLocalGroupsRequest$
user (2.models.netmgmt.User_1"P
GetUserLocalGroupsResponse2
local_groups (2.models.netmgmt.LocalGroup_1"A
ChangeUserPasswordRequest$
user (2.models.netmgmt.User_3"
ChangeUserPasswordResponse"9
EnableUserRequest$
user (2.models.netmgmt.User_1"
EnableUserResponse":
DisableUserRequest$
user (2.models.netmgmt.User_1"
DisableUserResponseB5Z3github.com/s77rt/rdpcloud/proto/go/services/netmgmtbproto3'
        , true);

        static::$is_initialized = true;
    }
}

