// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: models/fileio/quota_entry.proto

package fileio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	QuotaThreshold int64  `protobuf:"varint,2,opt,name=quota_threshold,json=quotaThreshold,proto3" json:"quota_threshold,omitempty"`
	QuotaLimit     int64  `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
	QuotaUsed      int64  `protobuf:"varint,4,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	AccountStatus  uint32 `protobuf:"varint,5,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
}

func (x *QuotaEntry) Reset() {
	*x = QuotaEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_fileio_quota_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaEntry) ProtoMessage() {}

func (x *QuotaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_models_fileio_quota_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaEntry.ProtoReflect.Descriptor instead.
func (*QuotaEntry) Descriptor() ([]byte, []int) {
	return file_models_fileio_quota_entry_proto_rawDescGZIP(), []int{0}
}

func (x *QuotaEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QuotaEntry) GetQuotaThreshold() int64 {
	if x != nil {
		return x.QuotaThreshold
	}
	return 0
}

func (x *QuotaEntry) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

func (x *QuotaEntry) GetQuotaUsed() int64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

func (x *QuotaEntry) GetAccountStatus() uint32 {
	if x != nil {
		return x.AccountStatus
	}
	return 0
}

type QuotaEntry_6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaThreshold int64 `protobuf:"varint,2,opt,name=quota_threshold,json=quotaThreshold,proto3" json:"quota_threshold,omitempty"`
	QuotaLimit     int64 `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
}

func (x *QuotaEntry_6) Reset() {
	*x = QuotaEntry_6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_fileio_quota_entry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaEntry_6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaEntry_6) ProtoMessage() {}

func (x *QuotaEntry_6) ProtoReflect() protoreflect.Message {
	mi := &file_models_fileio_quota_entry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaEntry_6.ProtoReflect.Descriptor instead.
func (*QuotaEntry_6) Descriptor() ([]byte, []int) {
	return file_models_fileio_quota_entry_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaEntry_6) GetQuotaThreshold() int64 {
	if x != nil {
		return x.QuotaThreshold
	}
	return 0
}

func (x *QuotaEntry_6) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

type QuotaEntry_30 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaThreshold int64  `protobuf:"varint,2,opt,name=quota_threshold,json=quotaThreshold,proto3" json:"quota_threshold,omitempty"`
	QuotaLimit     int64  `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
	QuotaUsed      int64  `protobuf:"varint,4,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	AccountStatus  uint32 `protobuf:"varint,5,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
}

func (x *QuotaEntry_30) Reset() {
	*x = QuotaEntry_30{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_fileio_quota_entry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaEntry_30) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaEntry_30) ProtoMessage() {}

func (x *QuotaEntry_30) ProtoReflect() protoreflect.Message {
	mi := &file_models_fileio_quota_entry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaEntry_30.ProtoReflect.Descriptor instead.
func (*QuotaEntry_30) Descriptor() ([]byte, []int) {
	return file_models_fileio_quota_entry_proto_rawDescGZIP(), []int{2}
}

func (x *QuotaEntry_30) GetQuotaThreshold() int64 {
	if x != nil {
		return x.QuotaThreshold
	}
	return 0
}

func (x *QuotaEntry_30) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

func (x *QuotaEntry_30) GetQuotaUsed() int64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

func (x *QuotaEntry_30) GetAccountStatus() uint32 {
	if x != nil {
		return x.AccountStatus
	}
	return 0
}

var File_models_fileio_quota_entry_proto protoreflect.FileDescriptor

var file_models_fileio_quota_entry_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2f,
	0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f,
	0x22, 0xb8, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x75,
	0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x55, 0x73, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x58, 0x0a, 0x0c, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x36, 0x12, 0x27, 0x0a, 0x0f, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x33, 0x30, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x55, 0x73, 0x65, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64, 0x70, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_models_fileio_quota_entry_proto_rawDescOnce sync.Once
	file_models_fileio_quota_entry_proto_rawDescData = file_models_fileio_quota_entry_proto_rawDesc
)

func file_models_fileio_quota_entry_proto_rawDescGZIP() []byte {
	file_models_fileio_quota_entry_proto_rawDescOnce.Do(func() {
		file_models_fileio_quota_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_fileio_quota_entry_proto_rawDescData)
	})
	return file_models_fileio_quota_entry_proto_rawDescData
}

var file_models_fileio_quota_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_fileio_quota_entry_proto_goTypes = []interface{}{
	(*QuotaEntry)(nil),    // 0: models.fileio.QuotaEntry
	(*QuotaEntry_6)(nil),  // 1: models.fileio.QuotaEntry_6
	(*QuotaEntry_30)(nil), // 2: models.fileio.QuotaEntry_30
}
var file_models_fileio_quota_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_fileio_quota_entry_proto_init() }
func file_models_fileio_quota_entry_proto_init() {
	if File_models_fileio_quota_entry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_fileio_quota_entry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_fileio_quota_entry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaEntry_6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_fileio_quota_entry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaEntry_30); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_fileio_quota_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_fileio_quota_entry_proto_goTypes,
		DependencyIndexes: file_models_fileio_quota_entry_proto_depIdxs,
		MessageInfos:      file_models_fileio_quota_entry_proto_msgTypes,
	}.Build()
	File_models_fileio_quota_entry_proto = out.File
	file_models_fileio_quota_entry_proto_rawDesc = nil
	file_models_fileio_quota_entry_proto_goTypes = nil
	file_models_fileio_quota_entry_proto_depIdxs = nil
}
