// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: services/secauthz/basic_access_control.proto

package secauthz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupAccountSidByUsernameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *LookupAccountSidByUsernameRequest) Reset() {
	*x = LookupAccountSidByUsernameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountSidByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountSidByUsernameRequest) ProtoMessage() {}

func (x *LookupAccountSidByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountSidByUsernameRequest.ProtoReflect.Descriptor instead.
func (*LookupAccountSidByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{0}
}

func (x *LookupAccountSidByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LookupAccountSidByUsernameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *LookupAccountSidByUsernameResponse) Reset() {
	*x = LookupAccountSidByUsernameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountSidByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountSidByUsernameResponse) ProtoMessage() {}

func (x *LookupAccountSidByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountSidByUsernameResponse.ProtoReflect.Descriptor instead.
func (*LookupAccountSidByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{1}
}

func (x *LookupAccountSidByUsernameResponse) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type LookupAccountUsernameBySidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *LookupAccountUsernameBySidRequest) Reset() {
	*x = LookupAccountUsernameBySidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountUsernameBySidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountUsernameBySidRequest) ProtoMessage() {}

func (x *LookupAccountUsernameBySidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountUsernameBySidRequest.ProtoReflect.Descriptor instead.
func (*LookupAccountUsernameBySidRequest) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{2}
}

func (x *LookupAccountUsernameBySidRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type LookupAccountUsernameBySidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *LookupAccountUsernameBySidResponse) Reset() {
	*x = LookupAccountUsernameBySidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountUsernameBySidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountUsernameBySidResponse) ProtoMessage() {}

func (x *LookupAccountUsernameBySidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountUsernameBySidResponse.ProtoReflect.Descriptor instead.
func (*LookupAccountUsernameBySidResponse) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{3}
}

func (x *LookupAccountUsernameBySidResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_services_secauthz_basic_access_control_proto protoreflect.FileDescriptor

var file_services_secauthz_basic_access_control_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74, 0x68,
	0x7a, 0x22, 0x3f, 0x0a, 0x21, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x69, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x36, 0x0a, 0x22, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x69, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x21, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x79, 0x53, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x22, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x53, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64, 0x70, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_secauthz_basic_access_control_proto_rawDescOnce sync.Once
	file_services_secauthz_basic_access_control_proto_rawDescData = file_services_secauthz_basic_access_control_proto_rawDesc
)

func file_services_secauthz_basic_access_control_proto_rawDescGZIP() []byte {
	file_services_secauthz_basic_access_control_proto_rawDescOnce.Do(func() {
		file_services_secauthz_basic_access_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_secauthz_basic_access_control_proto_rawDescData)
	})
	return file_services_secauthz_basic_access_control_proto_rawDescData
}

var file_services_secauthz_basic_access_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_secauthz_basic_access_control_proto_goTypes = []interface{}{
	(*LookupAccountSidByUsernameRequest)(nil),  // 0: services.secauthz.LookupAccountSidByUsernameRequest
	(*LookupAccountSidByUsernameResponse)(nil), // 1: services.secauthz.LookupAccountSidByUsernameResponse
	(*LookupAccountUsernameBySidRequest)(nil),  // 2: services.secauthz.LookupAccountUsernameBySidRequest
	(*LookupAccountUsernameBySidResponse)(nil), // 3: services.secauthz.LookupAccountUsernameBySidResponse
}
var file_services_secauthz_basic_access_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_secauthz_basic_access_control_proto_init() }
func file_services_secauthz_basic_access_control_proto_init() {
	if File_services_secauthz_basic_access_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_secauthz_basic_access_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountSidByUsernameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountSidByUsernameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountUsernameBySidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountUsernameBySidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_secauthz_basic_access_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_secauthz_basic_access_control_proto_goTypes,
		DependencyIndexes: file_services_secauthz_basic_access_control_proto_depIdxs,
		MessageInfos:      file_services_secauthz_basic_access_control_proto_msgTypes,
	}.Build()
	File_services_secauthz_basic_access_control_proto = out.File
	file_services_secauthz_basic_access_control_proto_rawDesc = nil
	file_services_secauthz_basic_access_control_proto_goTypes = nil
	file_services_secauthz_basic_access_control_proto_depIdxs = nil
}
