// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: services/secauthz/basic_access_control.proto

package secauthz

import (
	secauthz "github.com/s77rt/rdpcloud/proto/go/models/secauthz"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupAccountByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *secauthz.User_1 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LookupAccountByNameRequest) Reset() {
	*x = LookupAccountByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountByNameRequest) ProtoMessage() {}

func (x *LookupAccountByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountByNameRequest.ProtoReflect.Descriptor instead.
func (*LookupAccountByNameRequest) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{0}
}

func (x *LookupAccountByNameRequest) GetUser() *secauthz.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

type LookupAccountByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *LookupAccountByNameResponse) Reset() {
	*x = LookupAccountByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountByNameResponse) ProtoMessage() {}

func (x *LookupAccountByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountByNameResponse.ProtoReflect.Descriptor instead.
func (*LookupAccountByNameResponse) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{1}
}

func (x *LookupAccountByNameResponse) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type LookupAccountBySidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *LookupAccountBySidRequest) Reset() {
	*x = LookupAccountBySidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountBySidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountBySidRequest) ProtoMessage() {}

func (x *LookupAccountBySidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountBySidRequest.ProtoReflect.Descriptor instead.
func (*LookupAccountBySidRequest) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{2}
}

func (x *LookupAccountBySidRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type LookupAccountBySidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *secauthz.User_1 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LookupAccountBySidResponse) Reset() {
	*x = LookupAccountBySidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secauthz_basic_access_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupAccountBySidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountBySidResponse) ProtoMessage() {}

func (x *LookupAccountBySidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_secauthz_basic_access_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAccountBySidResponse.ProtoReflect.Descriptor instead.
func (*LookupAccountBySidResponse) Descriptor() ([]byte, []int) {
	return file_services_secauthz_basic_access_control_proto_rawDescGZIP(), []int{3}
}

func (x *LookupAccountBySidResponse) GetUser() *secauthz.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

var File_services_secauthz_basic_access_control_proto protoreflect.FileDescriptor

var file_services_secauthz_basic_access_control_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74, 0x68,
	0x7a, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x1a, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x5f, 0x31, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x1b, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x19, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x53, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x1a, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x53, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x73, 0x65,
	0x63, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x31, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64, 0x70, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_secauthz_basic_access_control_proto_rawDescOnce sync.Once
	file_services_secauthz_basic_access_control_proto_rawDescData = file_services_secauthz_basic_access_control_proto_rawDesc
)

func file_services_secauthz_basic_access_control_proto_rawDescGZIP() []byte {
	file_services_secauthz_basic_access_control_proto_rawDescOnce.Do(func() {
		file_services_secauthz_basic_access_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_secauthz_basic_access_control_proto_rawDescData)
	})
	return file_services_secauthz_basic_access_control_proto_rawDescData
}

var file_services_secauthz_basic_access_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_secauthz_basic_access_control_proto_goTypes = []interface{}{
	(*LookupAccountByNameRequest)(nil),  // 0: services.secauthz.LookupAccountByNameRequest
	(*LookupAccountByNameResponse)(nil), // 1: services.secauthz.LookupAccountByNameResponse
	(*LookupAccountBySidRequest)(nil),   // 2: services.secauthz.LookupAccountBySidRequest
	(*LookupAccountBySidResponse)(nil),  // 3: services.secauthz.LookupAccountBySidResponse
	(*secauthz.User_1)(nil),             // 4: models.secauthz.User_1
}
var file_services_secauthz_basic_access_control_proto_depIdxs = []int32{
	4, // 0: services.secauthz.LookupAccountByNameRequest.user:type_name -> models.secauthz.User_1
	4, // 1: services.secauthz.LookupAccountBySidResponse.user:type_name -> models.secauthz.User_1
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_secauthz_basic_access_control_proto_init() }
func file_services_secauthz_basic_access_control_proto_init() {
	if File_services_secauthz_basic_access_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_secauthz_basic_access_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountBySidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_secauthz_basic_access_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupAccountBySidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_secauthz_basic_access_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_secauthz_basic_access_control_proto_goTypes,
		DependencyIndexes: file_services_secauthz_basic_access_control_proto_depIdxs,
		MessageInfos:      file_services_secauthz_basic_access_control_proto_msgTypes,
	}.Build()
	File_services_secauthz_basic_access_control_proto = out.File
	file_services_secauthz_basic_access_control_proto_rawDesc = nil
	file_services_secauthz_basic_access_control_proto_goTypes = nil
	file_services_secauthz_basic_access_control_proto_depIdxs = nil
}
