// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: services/secauthz/secauthz.proto

package secauthz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecauthzClient is the client API for Secauthz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecauthzClient interface {
	LookupAccountSidByUsername(ctx context.Context, in *LookupAccountSidByUsernameRequest, opts ...grpc.CallOption) (*LookupAccountSidByUsernameResponse, error)
	LookupAccountUsernameBySid(ctx context.Context, in *LookupAccountUsernameBySidRequest, opts ...grpc.CallOption) (*LookupAccountUsernameBySidResponse, error)
}

type secauthzClient struct {
	cc grpc.ClientConnInterface
}

func NewSecauthzClient(cc grpc.ClientConnInterface) SecauthzClient {
	return &secauthzClient{cc}
}

func (c *secauthzClient) LookupAccountSidByUsername(ctx context.Context, in *LookupAccountSidByUsernameRequest, opts ...grpc.CallOption) (*LookupAccountSidByUsernameResponse, error) {
	out := new(LookupAccountSidByUsernameResponse)
	err := c.cc.Invoke(ctx, "/services.secauthz.Secauthz/LookupAccountSidByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secauthzClient) LookupAccountUsernameBySid(ctx context.Context, in *LookupAccountUsernameBySidRequest, opts ...grpc.CallOption) (*LookupAccountUsernameBySidResponse, error) {
	out := new(LookupAccountUsernameBySidResponse)
	err := c.cc.Invoke(ctx, "/services.secauthz.Secauthz/LookupAccountUsernameBySid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecauthzServer is the server API for Secauthz service.
// All implementations must embed UnimplementedSecauthzServer
// for forward compatibility
type SecauthzServer interface {
	LookupAccountSidByUsername(context.Context, *LookupAccountSidByUsernameRequest) (*LookupAccountSidByUsernameResponse, error)
	LookupAccountUsernameBySid(context.Context, *LookupAccountUsernameBySidRequest) (*LookupAccountUsernameBySidResponse, error)
	mustEmbedUnimplementedSecauthzServer()
}

// UnimplementedSecauthzServer must be embedded to have forward compatible implementations.
type UnimplementedSecauthzServer struct {
}

func (UnimplementedSecauthzServer) LookupAccountSidByUsername(context.Context, *LookupAccountSidByUsernameRequest) (*LookupAccountSidByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupAccountSidByUsername not implemented")
}
func (UnimplementedSecauthzServer) LookupAccountUsernameBySid(context.Context, *LookupAccountUsernameBySidRequest) (*LookupAccountUsernameBySidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupAccountUsernameBySid not implemented")
}
func (UnimplementedSecauthzServer) mustEmbedUnimplementedSecauthzServer() {}

// UnsafeSecauthzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecauthzServer will
// result in compilation errors.
type UnsafeSecauthzServer interface {
	mustEmbedUnimplementedSecauthzServer()
}

func RegisterSecauthzServer(s grpc.ServiceRegistrar, srv SecauthzServer) {
	s.RegisterService(&Secauthz_ServiceDesc, srv)
}

func _Secauthz_LookupAccountSidByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAccountSidByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecauthzServer).LookupAccountSidByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.secauthz.Secauthz/LookupAccountSidByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecauthzServer).LookupAccountSidByUsername(ctx, req.(*LookupAccountSidByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secauthz_LookupAccountUsernameBySid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAccountUsernameBySidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecauthzServer).LookupAccountUsernameBySid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.secauthz.Secauthz/LookupAccountUsernameBySid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecauthzServer).LookupAccountUsernameBySid(ctx, req.(*LookupAccountUsernameBySidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Secauthz_ServiceDesc is the grpc.ServiceDesc for Secauthz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Secauthz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.secauthz.Secauthz",
	HandlerType: (*SecauthzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupAccountSidByUsername",
			Handler:    _Secauthz_LookupAccountSidByUsername_Handler,
		},
		{
			MethodName: "LookupAccountUsernameBySid",
			Handler:    _Secauthz_LookupAccountUsernameBySid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/secauthz/secauthz.proto",
}
