// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: services/fileio/disk_management.proto

package fileio

import (
	fileio "github.com/s77rt/rdpcloud/proto/go/models/fileio"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuotaStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
}

func (x *GetQuotaStateRequest) Reset() {
	*x = GetQuotaStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStateRequest) ProtoMessage() {}

func (x *GetQuotaStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStateRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaStateRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuotaStateRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

type GetQuotaStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaState uint32 `protobuf:"varint,1,opt,name=quota_state,json=quotaState,proto3" json:"quota_state,omitempty"`
}

func (x *GetQuotaStateResponse) Reset() {
	*x = GetQuotaStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStateResponse) ProtoMessage() {}

func (x *GetQuotaStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStateResponse.ProtoReflect.Descriptor instead.
func (*GetQuotaStateResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuotaStateResponse) GetQuotaState() uint32 {
	if x != nil {
		return x.QuotaState
	}
	return 0
}

type SetQuotaStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	QuotaState uint32 `protobuf:"varint,2,opt,name=quota_state,json=quotaState,proto3" json:"quota_state,omitempty"`
}

func (x *SetQuotaStateRequest) Reset() {
	*x = SetQuotaStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetQuotaStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaStateRequest) ProtoMessage() {}

func (x *SetQuotaStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaStateRequest.ProtoReflect.Descriptor instead.
func (*SetQuotaStateRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{2}
}

func (x *SetQuotaStateRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *SetQuotaStateRequest) GetQuotaState() uint32 {
	if x != nil {
		return x.QuotaState
	}
	return 0
}

type SetQuotaStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetQuotaStateResponse) Reset() {
	*x = SetQuotaStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetQuotaStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaStateResponse) ProtoMessage() {}

func (x *SetQuotaStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaStateResponse.ProtoReflect.Descriptor instead.
func (*SetQuotaStateResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{3}
}

type GetDefaultQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
}

func (x *GetDefaultQuotaRequest) Reset() {
	*x = GetDefaultQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultQuotaRequest) ProtoMessage() {}

func (x *GetDefaultQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultQuotaRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetDefaultQuotaRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

type GetDefaultQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultQuota *fileio.QuotaEntry_6 `protobuf:"bytes,1,opt,name=default_quota,json=defaultQuota,proto3" json:"default_quota,omitempty"`
}

func (x *GetDefaultQuotaResponse) Reset() {
	*x = GetDefaultQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultQuotaResponse) ProtoMessage() {}

func (x *GetDefaultQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultQuotaResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetDefaultQuotaResponse) GetDefaultQuota() *fileio.QuotaEntry_6 {
	if x != nil {
		return x.DefaultQuota
	}
	return nil
}

type SetDefaultQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath   string               `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	DefaultQuota *fileio.QuotaEntry_6 `protobuf:"bytes,2,opt,name=default_quota,json=defaultQuota,proto3" json:"default_quota,omitempty"`
}

func (x *SetDefaultQuotaRequest) Reset() {
	*x = SetDefaultQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultQuotaRequest) ProtoMessage() {}

func (x *SetDefaultQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultQuotaRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultQuotaRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{6}
}

func (x *SetDefaultQuotaRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *SetDefaultQuotaRequest) GetDefaultQuota() *fileio.QuotaEntry_6 {
	if x != nil {
		return x.DefaultQuota
	}
	return nil
}

type SetDefaultQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDefaultQuotaResponse) Reset() {
	*x = SetDefaultQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultQuotaResponse) ProtoMessage() {}

func (x *SetDefaultQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultQuotaResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultQuotaResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{7}
}

type GetUsersQuotaEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
}

func (x *GetUsersQuotaEntriesRequest) Reset() {
	*x = GetUsersQuotaEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersQuotaEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersQuotaEntriesRequest) ProtoMessage() {}

func (x *GetUsersQuotaEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersQuotaEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetUsersQuotaEntriesRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetUsersQuotaEntriesRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

type GetUsersQuotaEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaEntries []*fileio.QuotaEntry `protobuf:"bytes,1,rep,name=quota_entries,json=quotaEntries,proto3" json:"quota_entries,omitempty"`
}

func (x *GetUsersQuotaEntriesResponse) Reset() {
	*x = GetUsersQuotaEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersQuotaEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersQuotaEntriesResponse) ProtoMessage() {}

func (x *GetUsersQuotaEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersQuotaEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetUsersQuotaEntriesResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{9}
}

func (x *GetUsersQuotaEntriesResponse) GetQuotaEntries() []*fileio.QuotaEntry {
	if x != nil {
		return x.QuotaEntries
	}
	return nil
}

type GetUserQuotaEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string         `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	User       *fileio.User_1 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserQuotaEntryRequest) Reset() {
	*x = GetUserQuotaEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserQuotaEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserQuotaEntryRequest) ProtoMessage() {}

func (x *GetUserQuotaEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserQuotaEntryRequest.ProtoReflect.Descriptor instead.
func (*GetUserQuotaEntryRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserQuotaEntryRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *GetUserQuotaEntryRequest) GetUser() *fileio.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserQuotaEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaEntry *fileio.QuotaEntry_30 `protobuf:"bytes,1,opt,name=quota_entry,json=quotaEntry,proto3" json:"quota_entry,omitempty"`
}

func (x *GetUserQuotaEntryResponse) Reset() {
	*x = GetUserQuotaEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserQuotaEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserQuotaEntryResponse) ProtoMessage() {}

func (x *GetUserQuotaEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserQuotaEntryResponse.ProtoReflect.Descriptor instead.
func (*GetUserQuotaEntryResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserQuotaEntryResponse) GetQuotaEntry() *fileio.QuotaEntry_30 {
	if x != nil {
		return x.QuotaEntry
	}
	return nil
}

type GetMyUserQuotaEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
}

func (x *GetMyUserQuotaEntryRequest) Reset() {
	*x = GetMyUserQuotaEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyUserQuotaEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUserQuotaEntryRequest) ProtoMessage() {}

func (x *GetMyUserQuotaEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUserQuotaEntryRequest.ProtoReflect.Descriptor instead.
func (*GetMyUserQuotaEntryRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyUserQuotaEntryRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

type GetMyUserQuotaEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaEntry *fileio.QuotaEntry_30 `protobuf:"bytes,1,opt,name=quota_entry,json=quotaEntry,proto3" json:"quota_entry,omitempty"`
}

func (x *GetMyUserQuotaEntryResponse) Reset() {
	*x = GetMyUserQuotaEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyUserQuotaEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUserQuotaEntryResponse) ProtoMessage() {}

func (x *GetMyUserQuotaEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUserQuotaEntryResponse.ProtoReflect.Descriptor instead.
func (*GetMyUserQuotaEntryResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{13}
}

func (x *GetMyUserQuotaEntryResponse) GetQuotaEntry() *fileio.QuotaEntry_30 {
	if x != nil {
		return x.QuotaEntry
	}
	return nil
}

type SetUserQuotaEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string               `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	User       *fileio.User_1       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	QuotaEntry *fileio.QuotaEntry_6 `protobuf:"bytes,3,opt,name=quota_entry,json=quotaEntry,proto3" json:"quota_entry,omitempty"`
}

func (x *SetUserQuotaEntryRequest) Reset() {
	*x = SetUserQuotaEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserQuotaEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserQuotaEntryRequest) ProtoMessage() {}

func (x *SetUserQuotaEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserQuotaEntryRequest.ProtoReflect.Descriptor instead.
func (*SetUserQuotaEntryRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{14}
}

func (x *SetUserQuotaEntryRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *SetUserQuotaEntryRequest) GetUser() *fileio.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SetUserQuotaEntryRequest) GetQuotaEntry() *fileio.QuotaEntry_6 {
	if x != nil {
		return x.QuotaEntry
	}
	return nil
}

type SetUserQuotaEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetUserQuotaEntryResponse) Reset() {
	*x = SetUserQuotaEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserQuotaEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserQuotaEntryResponse) ProtoMessage() {}

func (x *SetUserQuotaEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserQuotaEntryResponse.ProtoReflect.Descriptor instead.
func (*SetUserQuotaEntryResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{15}
}

type DeleteUserQuotaEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumePath string         `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	User       *fileio.User_1 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *DeleteUserQuotaEntryRequest) Reset() {
	*x = DeleteUserQuotaEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserQuotaEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserQuotaEntryRequest) ProtoMessage() {}

func (x *DeleteUserQuotaEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserQuotaEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserQuotaEntryRequest) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserQuotaEntryRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *DeleteUserQuotaEntryRequest) GetUser() *fileio.User_1 {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserQuotaEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserQuotaEntryResponse) Reset() {
	*x = DeleteUserQuotaEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fileio_disk_management_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserQuotaEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserQuotaEntryResponse) ProtoMessage() {}

func (x *DeleteUserQuotaEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fileio_disk_management_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserQuotaEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserQuotaEntryResponse) Descriptor() ([]byte, []int) {
	return file_services_fileio_disk_management_proto_rawDescGZIP(), []int{17}
}

var File_services_fileio_disk_management_proto protoreflect.FileDescriptor

var file_services_fileio_disk_management_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69,
	0x6f, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x1a, 0x1f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x38, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74,
	0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x58, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x22, 0x5b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x5f, 0x36, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x22, 0x7b, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x40, 0x0a, 0x0d,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x69, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x36,
	0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5e, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f,
	0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x66, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x69, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x31, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x5a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x69, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x33,
	0x30, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x3d, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5c, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f,
	0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x33, 0x30, 0x52, 0x0a,
	0x71, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0xa4, 0x01, 0x0a, 0x18, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x31, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x5f, 0x36, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x69,
	0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x5f, 0x31, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x37, 0x37, 0x72, 0x74, 0x2f, 0x72, 0x64,
	0x70, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_fileio_disk_management_proto_rawDescOnce sync.Once
	file_services_fileio_disk_management_proto_rawDescData = file_services_fileio_disk_management_proto_rawDesc
)

func file_services_fileio_disk_management_proto_rawDescGZIP() []byte {
	file_services_fileio_disk_management_proto_rawDescOnce.Do(func() {
		file_services_fileio_disk_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_fileio_disk_management_proto_rawDescData)
	})
	return file_services_fileio_disk_management_proto_rawDescData
}

var file_services_fileio_disk_management_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_services_fileio_disk_management_proto_goTypes = []interface{}{
	(*GetQuotaStateRequest)(nil),         // 0: services.fileio.GetQuotaStateRequest
	(*GetQuotaStateResponse)(nil),        // 1: services.fileio.GetQuotaStateResponse
	(*SetQuotaStateRequest)(nil),         // 2: services.fileio.SetQuotaStateRequest
	(*SetQuotaStateResponse)(nil),        // 3: services.fileio.SetQuotaStateResponse
	(*GetDefaultQuotaRequest)(nil),       // 4: services.fileio.GetDefaultQuotaRequest
	(*GetDefaultQuotaResponse)(nil),      // 5: services.fileio.GetDefaultQuotaResponse
	(*SetDefaultQuotaRequest)(nil),       // 6: services.fileio.SetDefaultQuotaRequest
	(*SetDefaultQuotaResponse)(nil),      // 7: services.fileio.SetDefaultQuotaResponse
	(*GetUsersQuotaEntriesRequest)(nil),  // 8: services.fileio.GetUsersQuotaEntriesRequest
	(*GetUsersQuotaEntriesResponse)(nil), // 9: services.fileio.GetUsersQuotaEntriesResponse
	(*GetUserQuotaEntryRequest)(nil),     // 10: services.fileio.GetUserQuotaEntryRequest
	(*GetUserQuotaEntryResponse)(nil),    // 11: services.fileio.GetUserQuotaEntryResponse
	(*GetMyUserQuotaEntryRequest)(nil),   // 12: services.fileio.GetMyUserQuotaEntryRequest
	(*GetMyUserQuotaEntryResponse)(nil),  // 13: services.fileio.GetMyUserQuotaEntryResponse
	(*SetUserQuotaEntryRequest)(nil),     // 14: services.fileio.SetUserQuotaEntryRequest
	(*SetUserQuotaEntryResponse)(nil),    // 15: services.fileio.SetUserQuotaEntryResponse
	(*DeleteUserQuotaEntryRequest)(nil),  // 16: services.fileio.DeleteUserQuotaEntryRequest
	(*DeleteUserQuotaEntryResponse)(nil), // 17: services.fileio.DeleteUserQuotaEntryResponse
	(*fileio.QuotaEntry_6)(nil),          // 18: models.fileio.QuotaEntry_6
	(*fileio.QuotaEntry)(nil),            // 19: models.fileio.QuotaEntry
	(*fileio.User_1)(nil),                // 20: models.fileio.User_1
	(*fileio.QuotaEntry_30)(nil),         // 21: models.fileio.QuotaEntry_30
}
var file_services_fileio_disk_management_proto_depIdxs = []int32{
	18, // 0: services.fileio.GetDefaultQuotaResponse.default_quota:type_name -> models.fileio.QuotaEntry_6
	18, // 1: services.fileio.SetDefaultQuotaRequest.default_quota:type_name -> models.fileio.QuotaEntry_6
	19, // 2: services.fileio.GetUsersQuotaEntriesResponse.quota_entries:type_name -> models.fileio.QuotaEntry
	20, // 3: services.fileio.GetUserQuotaEntryRequest.user:type_name -> models.fileio.User_1
	21, // 4: services.fileio.GetUserQuotaEntryResponse.quota_entry:type_name -> models.fileio.QuotaEntry_30
	21, // 5: services.fileio.GetMyUserQuotaEntryResponse.quota_entry:type_name -> models.fileio.QuotaEntry_30
	20, // 6: services.fileio.SetUserQuotaEntryRequest.user:type_name -> models.fileio.User_1
	18, // 7: services.fileio.SetUserQuotaEntryRequest.quota_entry:type_name -> models.fileio.QuotaEntry_6
	20, // 8: services.fileio.DeleteUserQuotaEntryRequest.user:type_name -> models.fileio.User_1
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_services_fileio_disk_management_proto_init() }
func file_services_fileio_disk_management_proto_init() {
	if File_services_fileio_disk_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_fileio_disk_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetQuotaStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetQuotaStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersQuotaEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersQuotaEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserQuotaEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserQuotaEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyUserQuotaEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyUserQuotaEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserQuotaEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserQuotaEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserQuotaEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fileio_disk_management_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserQuotaEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_fileio_disk_management_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_fileio_disk_management_proto_goTypes,
		DependencyIndexes: file_services_fileio_disk_management_proto_depIdxs,
		MessageInfos:      file_services_fileio_disk_management_proto_msgTypes,
	}.Build()
	File_services_fileio_disk_management_proto = out.File
	file_services_fileio_disk_management_proto_rawDesc = nil
	file_services_fileio_disk_management_proto_goTypes = nil
	file_services_fileio_disk_management_proto_depIdxs = nil
}
