<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/netmgmt/user.proto

namespace GPBMetadata\Models\Netmgmt;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
€
models/netmgmt/user.protomodels.netmgmt"L
User
username (	
password (	
	privilege (
flags ("
User_1
username (	",
User_3
username (	
password (	B3Z1github.com/s77rt/rdpcloud/proto/go/models/netmgmtbproto3'
        , true);

        static::$is_initialized = true;
    }
}

