<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/secauthz/basic_access_control.proto

namespace GPBMetadata\Services\Secauthz;

class BasicAccessControl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Õ
,services/secauthz/basic_access_control.protoservices.secauthz"5
!LookupAccountSidByUsernameRequest
username (	"1
"LookupAccountSidByUsernameResponse
sid (	"0
!LookupAccountUsernameBySidRequest
sid (	"6
"LookupAccountUsernameBySidResponse
username (	B6Z4github.com/s77rt/rdpcloud/proto/go/services/secauthzbproto3'
        , true);

        static::$is_initialized = true;
    }
}

